import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

export default defineConfig({
  plugins: [react()],
  root: 'client',
  build: {
    outDir: '../dist',
    emptyOutDir: true,
    // The React app lives at /app/. The landing and content pages at / are
    // static HTML generated by site/build.js after this build.
    rollupOptions: {
      input: path.resolve(__dirname, 'client/app/index.html'),
    },
  },
  server: {
    port: 5173,
    proxy: {
      '/api': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      },
      '/_mirage': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      },
      '/examples': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      }
    }
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './client/src'),
    },
  },
})